# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: daisy
description: Broadcast scheduling app 📅
docs: true
docsurl: https://radio-aktywne.github.io/daisy
envprefix: DAISY
imagename: apps/daisy
keyprefix: daisy
port: 10810
registry: true
releases: true
reponame: daisy
repourl: https://github.com/radio-aktywne/daisy
