# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: webscheduler
description: Broadcast scheduling app 📅
docs: true
docsurl: https://radio-aktywne.github.io/webscheduler
envprefix: WEBSCHEDULER
imagename: apps/webscheduler
keyprefix: webscheduler
port: 32000
registry: true
releases: true
reponame: webscheduler
repourl: https://github.com/radio-aktywne/webscheduler
