// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * Datetime in UTC.
 */
export const UtcDatetimeSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime in UTC.",
  });

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

/**
 * Specification
 */
export const SpecificationSchema = z.object({
  type: z.string(),
  parameters: z.record(
    z.string(),
    z
      .union([
        z.record(z.string(), z.unknown()),
        z.array(z.unknown()),
        z.string(),
        z.int(),
        z.number(),
        z.boolean(),
      ])
      .nullable(),
  ),
});

/**
 * Task
 */
export const TaskSchema = z.object({
  id: z.uuid(),
  operation: SpecificationSchema,
  condition: SpecificationSchema,
  dependencies: z.record(z.string(), z.uuid()),
});

/**
 * EventType
 *
 * Event types.
 */
export const EventTypeSchema = z.enum(["test"]).register(z.globalRegistry, {
  description: "Event types.",
});

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(EventTypeSchema)])
  .nullable();

/**
 * Status
 *
 * Status of a task.
 */
export const StatusSchema = z
  .enum([
    "queued",
    "waiting",
    "sleeping",
    "running",
    "cancelled",
    "failed",
    "completed",
  ])
  .register(z.globalRegistry, {
    description: "Status of a task.",
  });

/**
 * QueuedTask
 *
 * Data of a queued task.
 */
export const ScheduleResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a queued task.",
  });

/**
 * ScheduleRequestModel
 *
 * Request to schedule a task.
 */
export const ScheduleRequestDataSchema = z
  .object({
    operation: SpecificationSchema,
    condition: SpecificationSchema,
    dependencies: z
      .record(z.string(), z.uuid())
      .register(z.globalRegistry, {
        description: "Dependencies of the task.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Request to schedule a task.",
  });

/**
 * TaskIndex
 *
 * Index of tasks by status.
 */
export const ListResponseTasksSchema = z
  .object({
    queued: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of queued tasks.",
    }),
    waiting: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of waiting tasks.",
    }),
    sleeping: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of sleeping tasks.",
    }),
    running: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of running tasks.",
    }),
    cancelled: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of cancelled tasks.",
    }),
    failed: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of failed tasks.",
    }),
    completed: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of completed tasks.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Index of tasks by status.",
  });

/**
 * WaitingTask
 *
 * Data of a waiting task.
 */
export const GetWaitingResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a waiting task.",
  });

export const GetWaitingRequestIdSchema = z.uuid();

/**
 * SleepingTask
 *
 * Data of a sleeping task.
 */
export const GetSleepingResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema.nullable(),
    slept: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a sleeping task.",
  });

export const GetSleepingRequestIdSchema = z.uuid();

/**
 * RunningTask
 *
 * Data of a running task.
 */
export const GetRunningResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema,
    started: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a running task.",
  });

export const GetRunningRequestIdSchema = z.uuid();

/**
 * GenericTask
 *
 * Data of a task of any status.
 */
export const GetResponseTaskSchema = z
  .object({
    task: TaskSchema,
    status: StatusSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a task of any status.",
  });

export const GetRequestIdSchema = z.uuid();

/**
 * QueuedTask
 *
 * Data of a queued task.
 */
export const GetQueuedResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a queued task.",
  });

export const GetQueuedRequestIdSchema = z.uuid();

/**
 * FailedTask
 *
 * Data of a failed task.
 */
export const GetFailedResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema,
    started: UtcDatetimeSchema.nullable(),
    failed: UtcDatetimeSchema,
    error: z.string().register(z.globalRegistry, {
      description: "Error message.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Data of a failed task.",
  });

export const GetFailedRequestIdSchema = z.uuid();

/**
 * CompletedTask
 *
 * Data of a completed task.
 */
export const GetCompletedResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema,
    started: UtcDatetimeSchema,
    completed: UtcDatetimeSchema,
    result: z
      .union([
        z.record(z.string(), z.unknown()),
        z.array(z.unknown()),
        z.string(),
        z.int(),
        z.number(),
        z.boolean(),
      ])
      .nullable(),
  })
  .register(z.globalRegistry, {
    description: "Data of a completed task.",
  });

export const GetCompletedRequestIdSchema = z.uuid();

/**
 * CancelledTask
 *
 * Data of a cancelled task.
 */
export const GetCancelledResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema,
    started: UtcDatetimeSchema.nullable(),
    cancelled: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a cancelled task.",
  });

export const GetCancelledRequestIdSchema = z.uuid();

/**
 * CleaningResult
 *
 * Result of cleaning.
 */
export const CleanResponseResultsSchema = z
  .object({
    removed: z.array(z.uuid()).register(z.globalRegistry, {
      description: "Identifiers of removed tasks.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of cleaning.",
  });

/**
 * CleanRequestModel
 *
 * Request to clean tasks.
 */
export const CleanRequestDataSchema = z
  .object({
    strategy: SpecificationSchema,
  })
  .register(z.globalRegistry, {
    description: "Request to clean tasks.",
  });

/**
 * CancelledTask
 *
 * Data of a cancelled task.
 */
export const CancelResponseTaskSchema = z
  .object({
    task: TaskSchema,
    enqueued: UtcDatetimeSchema,
    dequeued: UtcDatetimeSchema,
    started: UtcDatetimeSchema.nullable(),
    cancelled: UtcDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Data of a cancelled task.",
  });

export const CancelRequestIdSchema = z.uuid();

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const TasksIdCancelRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: CancelRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksIdCancelResponseSchema = CancelResponseTaskSchema;

export const TasksIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksIdGetResponseSchema = GetResponseTaskSchema;

export const TasksCleanCleanRequestSchema = z.object({
  body: CleanRequestDataSchema,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksCleanCleanResponseSchema = CleanResponseResultsSchema;

export const TasksCancelledIdGetCancelledRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetCancelledRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksCancelledIdGetCancelledResponseSchema =
  GetCancelledResponseTaskSchema;

export const TasksCompletedIdGetCompletedRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetCompletedRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksCompletedIdGetCompletedResponseSchema =
  GetCompletedResponseTaskSchema;

export const TasksFailedIdGetFailedRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetFailedRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksFailedIdGetFailedResponseSchema = GetFailedResponseTaskSchema;

export const TasksQueuedIdGetQueuedRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetQueuedRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksQueuedIdGetQueuedResponseSchema = GetQueuedResponseTaskSchema;

export const TasksRunningIdGetRunningRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetRunningRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksRunningIdGetRunningResponseSchema =
  GetRunningResponseTaskSchema;

export const TasksSleepingIdGetSleepingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetSleepingRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksSleepingIdGetSleepingResponseSchema =
  GetSleepingResponseTaskSchema;

export const TasksWaitingIdGetWaitingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: GetWaitingRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksWaitingIdGetWaitingResponseSchema =
  GetWaitingResponseTaskSchema;

export const TasksListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TasksListResponseSchema = ListResponseTasksSchema;

export const TasksScheduleRequestSchema = z.object({
  body: ScheduleRequestDataSchema,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Document created, URL follows
 */
export const TasksScheduleResponseSchema = ScheduleResponseTaskSchema;

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;
