// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

/**
 * Task
 */
export type Task = {
  /**
   * Id
   */
  id: string;
  operation: Specification;
  condition: Specification;
  /**
   * Dependencies
   */
  dependencies: {
    [key: string]: string;
  };
};

/**
 * Specification
 */
export type Specification = {
  /**
   * Type
   */
  type: string;
  /**
   * Parameters
   */
  parameters: {
    [key: string]:
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | string
      | number
      | number
      | boolean
      | null;
  };
};

export type SubscribeRequestTypes = string | Array<EventType> | null;

/**
 * EventType
 *
 * Event types.
 */
export type EventType = "test";

/**
 * Status
 *
 * Status of a task.
 */
export type Status =
  | "pending"
  | "running"
  | "cancelled"
  | "failed"
  | "completed";

/**
 * PendingTask
 *
 * Data of a pending task.
 */
export type ScheduleResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
};

export type NaiveDatetime = string;

/**
 * ScheduleRequestModel
 *
 * Request to schedule a task.
 */
export type ScheduleRequestData = {
  operation: Specification;
  condition: Specification;
  /**
   * Dependencies
   *
   * Dependencies of the task.
   */
  dependencies: {
    [key: string]: string;
  };
};

/**
 * TaskIndex
 *
 * Index of tasks by status.
 */
export type ListResponseTasks = {
  /**
   * Pending
   *
   * Identifiers of pending tasks.
   */
  pending: Array<string>;
  /**
   * Running
   *
   * Identifiers of running tasks.
   */
  running: Array<string>;
  /**
   * Cancelled
   *
   * Identifiers of cancelled tasks.
   */
  cancelled: Array<string>;
  /**
   * Failed
   *
   * Identifiers of failed tasks.
   */
  failed: Array<string>;
  /**
   * Completed
   *
   * Identifiers of completed tasks.
   */
  completed: Array<string>;
};

/**
 * RunningTask
 *
 * Data of a running task.
 */
export type GetRunningResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
  started: NaiveDatetime;
};

export type GetRunningRequestId = string;

/**
 * GenericTask
 *
 * Data of a task of any status.
 */
export type GetResponseTask = {
  task: Task;
  status: Status;
};

export type GetRequestId = string;

/**
 * PendingTask
 *
 * Data of a pending task.
 */
export type GetPendingResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
};

export type GetPendingRequestId = string;

/**
 * FailedTask
 *
 * Data of a failed task.
 */
export type GetFailedResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
  started: NaiveDatetime;
  failed: NaiveDatetime;
  /**
   * Error
   *
   * Error message.
   */
  error: string;
};

export type GetFailedRequestId = string;

/**
 * CompletedTask
 *
 * Data of a completed task.
 */
export type GetCompletedResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
  started: NaiveDatetime;
  completed: NaiveDatetime;
  /**
   * Result
   *
   * Result of the task.
   */
  result:
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | string
    | number
    | number
    | boolean
    | null;
};

export type GetCompletedRequestId = string;

/**
 * CancelledTask
 *
 * Data of a cancelled task.
 */
export type GetCancelledResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
  /**
   * Datetime in UTC when the task was started.
   */
  started: NaiveDatetime | null;
  cancelled: NaiveDatetime;
};

export type GetCancelledRequestId = string;

/**
 * CleaningResult
 *
 * Result of cleaning.
 */
export type CleanResponseResults = {
  /**
   * Removed
   *
   * Identifiers of removed tasks.
   */
  removed: Array<string>;
};

/**
 * CleanRequestModel
 *
 * Request to clean tasks.
 */
export type CleanRequestData = {
  strategy: Specification;
};

/**
 * CancelledTask
 *
 * Data of a cancelled task.
 */
export type CancelResponseTask = {
  task: Task;
  scheduled: NaiveDatetime;
  /**
   * Datetime in UTC when the task was started.
   */
  started: NaiveDatetime | null;
  cancelled: NaiveDatetime;
};

export type CancelRequestId = string;

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TasksIdCancelRequest = {
  body?: never;
  path: {
    id: CancelRequestId;
  };
  query?: never;
  url: "/tasks/{id}";
};

export type TasksIdCancelErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksIdCancelError = TasksIdCancelErrors[keyof TasksIdCancelErrors];

export type TasksIdCancelResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: CancelResponseTask;
};

export type TasksIdCancelResponse =
  TasksIdCancelResponses[keyof TasksIdCancelResponses];

export type TasksIdGetRequest = {
  body?: never;
  path: {
    id: GetRequestId;
  };
  query?: never;
  url: "/tasks/{id}";
};

export type TasksIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksIdGetError = TasksIdGetErrors[keyof TasksIdGetErrors];

export type TasksIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseTask;
};

export type TasksIdGetResponse = TasksIdGetResponses[keyof TasksIdGetResponses];

export type TasksCleanCleanRequest = {
  body: CleanRequestData;
  path?: never;
  query?: never;
  url: "/tasks/clean";
};

export type TasksCleanCleanErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksCleanCleanError =
  TasksCleanCleanErrors[keyof TasksCleanCleanErrors];

export type TasksCleanCleanResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: CleanResponseResults;
};

export type TasksCleanCleanResponse =
  TasksCleanCleanResponses[keyof TasksCleanCleanResponses];

export type TasksCancelledIdGetCancelledRequest = {
  body?: never;
  path: {
    id: GetCancelledRequestId;
  };
  query?: never;
  url: "/tasks/cancelled/{id}";
};

export type TasksCancelledIdGetCancelledErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksCancelledIdGetCancelledError =
  TasksCancelledIdGetCancelledErrors[keyof TasksCancelledIdGetCancelledErrors];

export type TasksCancelledIdGetCancelledResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetCancelledResponseTask;
};

export type TasksCancelledIdGetCancelledResponse =
  TasksCancelledIdGetCancelledResponses[keyof TasksCancelledIdGetCancelledResponses];

export type TasksCompletedIdGetCompletedRequest = {
  body?: never;
  path: {
    id: GetCompletedRequestId;
  };
  query?: never;
  url: "/tasks/completed/{id}";
};

export type TasksCompletedIdGetCompletedErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksCompletedIdGetCompletedError =
  TasksCompletedIdGetCompletedErrors[keyof TasksCompletedIdGetCompletedErrors];

export type TasksCompletedIdGetCompletedResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetCompletedResponseTask;
};

export type TasksCompletedIdGetCompletedResponse =
  TasksCompletedIdGetCompletedResponses[keyof TasksCompletedIdGetCompletedResponses];

export type TasksFailedIdGetFailedRequest = {
  body?: never;
  path: {
    id: GetFailedRequestId;
  };
  query?: never;
  url: "/tasks/failed/{id}";
};

export type TasksFailedIdGetFailedErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksFailedIdGetFailedError =
  TasksFailedIdGetFailedErrors[keyof TasksFailedIdGetFailedErrors];

export type TasksFailedIdGetFailedResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetFailedResponseTask;
};

export type TasksFailedIdGetFailedResponse =
  TasksFailedIdGetFailedResponses[keyof TasksFailedIdGetFailedResponses];

export type TasksPendingIdGetPendingRequest = {
  body?: never;
  path: {
    id: GetPendingRequestId;
  };
  query?: never;
  url: "/tasks/pending/{id}";
};

export type TasksPendingIdGetPendingErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksPendingIdGetPendingError =
  TasksPendingIdGetPendingErrors[keyof TasksPendingIdGetPendingErrors];

export type TasksPendingIdGetPendingResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetPendingResponseTask;
};

export type TasksPendingIdGetPendingResponse =
  TasksPendingIdGetPendingResponses[keyof TasksPendingIdGetPendingResponses];

export type TasksRunningIdGetRunningRequest = {
  body?: never;
  path: {
    id: GetRunningRequestId;
  };
  query?: never;
  url: "/tasks/running/{id}";
};

export type TasksRunningIdGetRunningErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksRunningIdGetRunningError =
  TasksRunningIdGetRunningErrors[keyof TasksRunningIdGetRunningErrors];

export type TasksRunningIdGetRunningResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetRunningResponseTask;
};

export type TasksRunningIdGetRunningResponse =
  TasksRunningIdGetRunningResponses[keyof TasksRunningIdGetRunningResponses];

export type TasksListRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/tasks";
};

export type TasksListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ListResponseTasks;
};

export type TasksListResponse = TasksListResponses[keyof TasksListResponses];

export type TasksScheduleRequest = {
  body: ScheduleRequestData;
  path?: never;
  query?: never;
  url: "/tasks";
};

export type TasksScheduleErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TasksScheduleError = TasksScheduleErrors[keyof TasksScheduleErrors];

export type TasksScheduleResponses = {
  /**
   * Document created, URL follows
   */
  201: ScheduleResponseTask;
};

export type TasksScheduleResponse =
  TasksScheduleResponses[keyof TasksScheduleResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
