/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/ping": {
    delete?: never;
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/tasks": {
    delete?: never;
    /**
     * Get index
     * @description List tasks.
     */
    get: operations["TasksList"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Schedule task
     * @description Schedule a task.
     */
    post: operations["TasksSchedule"];
    put?: never;
    trace?: never;
  };
  "/tasks/{id}": {
    /**
     * Cancel task
     * @description Cancel a task.
     */
    delete: operations["TasksIdCancel"];
    /**
     * Get task
     * @description Get a task.
     */
    get: operations["TasksIdGet"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/tasks/cancelled/{id}": {
    delete?: never;
    /**
     * Get cancelled task
     * @description Get a cancelled task.
     */
    get: operations["TasksCancelledIdGetCancelled"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/tasks/clean": {
    delete?: never;
    get?: never;
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Clean tasks
     * @description Clean tasks.
     */
    post: operations["TasksCleanClean"];
    put?: never;
    trace?: never;
  };
  "/tasks/completed/{id}": {
    delete?: never;
    /**
     * Get completed task
     * @description Get a completed task.
     */
    get: operations["TasksCompletedIdGetCompleted"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/tasks/failed/{id}": {
    delete?: never;
    /**
     * Get failed task
     * @description Get a failed task.
     */
    get: operations["TasksFailedIdGetFailed"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/tasks/pending/{id}": {
    delete?: never;
    /**
     * Get pending task
     * @description Get a pending task.
     */
    get: operations["TasksPendingIdGetPending"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/tasks/running/{id}": {
    delete?: never;
    /**
     * Get running task
     * @description Get a running task.
     */
    get: operations["TasksRunningIdGetRunning"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
};
export type webhooks = { [key: string]: never };
export type components = {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    /** CancelledTask */
    CancelledTask: {
      /**
       * Format: date-time
       * @description Date and time when the task was cancelled.
       */
      cancelled: string;
      /**
       * Format: date-time
       * @description Date and time when the task was scheduled.
       */
      scheduled: string;
      /** @description Date and time when the task was started. */
      started?: null | string;
      task: components["schemas"]["Task"];
    };
    /** CleaningResult */
    CleaningResult: {
      /** @description Identifiers of removed tasks. */
      removed: string[];
    };
    /**
     * CleanRequestModel
     * @description Data to clean tasks.
     */
    CleanRequestModel: {
      strategy: components["schemas"]["Specification"];
    };
    /** CompletedTask */
    CompletedTask: {
      /**
       * Format: date-time
       * @description Date and time when the task was completed.
       */
      completed: string;
      /** @description Result of the task. */
      result?:
        | {
            [key: string]: unknown;
          }
        | boolean
        | null
        | number
        | string
        | unknown[];
      /**
       * Format: date-time
       * @description Date and time when the task was scheduled.
       */
      scheduled: string;
      /**
       * Format: date-time
       * @description Date and time when the task was started.
       */
      started: string;
      task: components["schemas"]["Task"];
    };
    /** FailedTask */
    FailedTask: {
      /** @description Error message. */
      error: string;
      /**
       * Format: date-time
       * @description Date and time when the task failed.
       */
      failed: string;
      /**
       * Format: date-time
       * @description Date and time when the task was scheduled.
       */
      scheduled: string;
      /**
       * Format: date-time
       * @description Date and time when the task was started.
       */
      started: string;
      task: components["schemas"]["Task"];
    };
    /** GenericTask */
    GenericTask: {
      /**
       * @description Task status.
       * @enum {string}
       */
      status: "cancelled" | "completed" | "failed" | "pending" | "running";
      task: components["schemas"]["Task"];
    };
    /** PendingTask */
    PendingTask: {
      /**
       * Format: date-time
       * @description Date and time when the task was scheduled.
       */
      scheduled: string;
      task: components["schemas"]["Task"];
    };
    /** RunningTask */
    RunningTask: {
      /**
       * Format: date-time
       * @description Date and time when the task was scheduled.
       */
      scheduled: string;
      /**
       * Format: date-time
       * @description Date and time when the task was started.
       */
      started: string;
      task: components["schemas"]["Task"];
    };
    /**
     * ScheduleRequestModel
     * @description Data to schedule a task.
     */
    ScheduleRequestModel: {
      condition: components["schemas"]["Specification"];
      /** @description Dependencies of the task. */
      dependencies: {
        [key: string]: string;
      };
      operation: components["schemas"]["Specification"];
    };
    /** Specification */
    Specification: {
      parameters: {
        [key: string]:
          | {
              [key: string]: unknown;
            }
          | boolean
          | null
          | number
          | string
          | unknown[];
      };
      type: string;
    };
    /**
     * Task
     * @description Task data.
     */
    Task: {
      condition: components["schemas"]["Specification"];
      dependencies: {
        [key: string]: string;
      };
      /** Format: uuid */
      id: string;
      operation: components["schemas"]["Specification"];
    };
    /** TaskIndex */
    TaskIndex: {
      /** @description Identifiers of cancelled tasks. */
      cancelled: string[];
      /** @description Identifiers of completed tasks. */
      completed: string[];
      /** @description Identifiers of failed tasks. */
      failed: string[];
      /** @description Identifiers of pending tasks. */
      pending: string[];
      /** @description Identifiers of running tasks. */
      running: string[];
    };
  };
};
export type $defs = { [key: string]: never };
export type operations = {
  PingHeadping: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  PingPing: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  TasksCancelledIdGetCancelled: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["CancelledTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksCleanClean: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CleanRequestModel"];
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["CleaningResult"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksCompletedIdGetCompleted: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["CompletedTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksFailedIdGetFailed: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["FailedTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksIdCancel: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["CancelledTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksIdGet: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["GenericTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksList: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["TaskIndex"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksPendingIdGetPending: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["PendingTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksRunningIdGetRunning: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the task. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["RunningTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  TasksSchedule: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleRequestModel"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        content: {
          "application/json": components["schemas"]["PendingTask"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
};
