/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    /**
     * Ping
     * @description Do nothing.
     */
    get: operations["PingPing"];
  };
  "/tasks/{id}": {
    /**
     * Get task
     * @description Get task by id.
     */
    get: operations["TasksIdGetTask"];
    /**
     * Cancel task
     * @description Cancel a task.
     */
    delete: operations["TasksIdCancelTask"];
  };
  "/tasks/clean": {
    /**
     * Clean tasks
     * @description Clean stale tasks.
     */
    post: operations["TasksCleanCleanTasks"];
  };
  "/tasks/cancelled/{id}": {
    /**
     * Get cancelled task
     * @description Get cancelled task by id.
     */
    get: operations["TasksCancelledIdGetCancelledTask"];
  };
  "/tasks/completed/{id}": {
    /**
     * Get completed task
     * @description Get completed task by id.
     */
    get: operations["TasksCompletedIdGetCompletedTask"];
  };
  "/tasks/failed/{id}": {
    /**
     * Get failed task
     * @description Get failed task by id.
     */
    get: operations["TasksFailedIdGetFailedTask"];
  };
  "/tasks": {
    /**
     * Get index
     * @description Get tasks index.
     */
    get: operations["TasksGetIndex"];
    /**
     * Schedule task
     * @description Schedule a task.
     */
    post: operations["TasksScheduleTask"];
  };
  "/tasks/pending/{id}": {
    /**
     * Get pending task
     * @description Get pending task by id.
     */
    get: operations["TasksPendingIdGetPendingTask"];
  };
  "/tasks/running/{id}": {
    /**
     * Get running task
     * @description Get running task by id.
     */
    get: operations["TasksRunningIdGetRunningTask"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** GenericTask */
    GenericTask: {
      task: components["schemas"]["Task"];
      /** @enum {string} */
      status: "pending" | "running" | "cancelled" | "failed" | "completed";
    };
    /** Task */
    Task: {
      /** Format: uuid */
      id: string;
      operation: components["schemas"]["Specification"];
      condition: components["schemas"]["Specification"];
      dependencies: {
        [key: string]: string;
      };
    };
    /** Specification */
    Specification: {
      type: string;
      parameters: {
        [key: string]:
          | null
          | {
              [key: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean;
      };
    };
    /** CancelledTask */
    CancelledTask: {
      task: components["schemas"]["Task"];
      /** Format: date-time */
      scheduled: string;
      started?: null | string;
      /** Format: date-time */
      cancelled: string;
    };
    /** CleanRequest */
    CleanRequest: {
      strategy: components["schemas"]["Specification"];
    };
    /** CleaningResult */
    CleaningResult: {
      removed: string[];
    };
    /** CompletedTask */
    CompletedTask: {
      task: components["schemas"]["Task"];
      /** Format: date-time */
      scheduled: string;
      /** Format: date-time */
      started: string;
      /** Format: date-time */
      completed: string;
      result?:
        | null
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean;
    };
    /** FailedTask */
    FailedTask: {
      task: components["schemas"]["Task"];
      /** Format: date-time */
      scheduled: string;
      /** Format: date-time */
      started: string;
      /** Format: date-time */
      failed: string;
      error: string;
    };
    /** TaskIndex */
    TaskIndex: {
      pending: string[];
      running: string[];
      cancelled: string[];
      failed: string[];
      completed: string[];
    };
    /** ScheduleRequest */
    ScheduleRequest: {
      operation: components["schemas"]["Specification"];
      condition: components["schemas"]["Specification"];
      dependencies: {
        [key: string]: string;
      };
    };
    /** PendingTask */
    PendingTask: {
      task: components["schemas"]["Task"];
      /** Format: date-time */
      scheduled: string;
    };
    /** RunningTask */
    RunningTask: {
      task: components["schemas"]["Task"];
      /** Format: date-time */
      scheduled: string;
      /** Format: date-time */
      started: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Ping
   * @description Do nothing.
   */
  PingPing: {
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  /**
   * Get task
   * @description Get task by id.
   */
  TasksIdGetTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["GenericTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Cancel task
   * @description Cancel a task.
   */
  TasksIdCancelTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["CancelledTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Clean tasks
   * @description Clean stale tasks.
   */
  TasksCleanCleanTasks: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CleanRequest"];
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["CleaningResult"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Unprocessable Content */
      422: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get cancelled task
   * @description Get cancelled task by id.
   */
  TasksCancelledIdGetCancelledTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["CancelledTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get completed task
   * @description Get completed task by id.
   */
  TasksCompletedIdGetCompletedTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["CompletedTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get failed task
   * @description Get failed task by id.
   */
  TasksFailedIdGetFailedTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["FailedTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get index
   * @description Get tasks index.
   */
  TasksGetIndex: {
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["TaskIndex"];
        };
      };
    };
  };
  /**
   * Schedule task
   * @description Schedule a task.
   */
  TasksScheduleTask: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleRequest"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {};
        content: {
          "application/json": components["schemas"]["PendingTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Unprocessable Content */
      422: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get pending task
   * @description Get pending task by id.
   */
  TasksPendingIdGetPendingTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["PendingTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get running task
   * @description Get running task by id.
   */
  TasksRunningIdGetRunningTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["RunningTask"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
}
